name = "replica-backend"
main = "src/index.js"
compatibility_date = "2024-11-20"

[vars]
NODE_ENV = "production"

[[kv_namespaces]]
binding = "REPLICA_DATA"
id = "9618271d9bb44030b90ea573ef63966c"

[[d1_databases]]
binding = "DB"
database_name = "replica_backend_db"
database_id = "a1dbe241-c817-4249-a426-8d3bb5b286ef"
